apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kataforfun
  name: kataforfun
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kataforfun
  strategy: {}
  template:
    metadata:
      labels:
        app: kataforfun
    spec:
      containers:
      - image: replace
        name: kataforfun-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kataforfun
  name: kataforfun-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kataforfun
  type: NodePort